'use strict';
angular.module('app').config(['$stateProvider','$urlRouterProvider',function($stateProvider,$urlRouterProvider){
	$stateProvider.state('main',{
		url:'/main',
		templateUrl:'view/main.html',
		controller:'mainCtrl'
	}).state('search',{ 
		url:'/search/:name',
		templateUrl:'view/search.html',
		controller:'searchCtrl'
	}).state('my',{ 
		url:'/my',
		templateUrl:'view/my.html',
		controller:'myCtrl'
	}).state('login',{ 
		url:'/login',
		templateUrl:'view/login.html',
		controller:'loginCtrl'
	}).state('personRegist',{ 
		url:'/personRegist',
		templateUrl:'view/personRegist.html',
		controller:'registCtrl'
	}).state('detail',{ 
		url:'/detail/:id',
		templateUrl:'view/template/detail.html',
		controller:'detailCtrl'
	}).state('collectCode',{ 
		url:'/collectCode',
		templateUrl:'view/template/collectCode.html',
		controller:'collectCodeCtrl'
	}).state('deliverRecord',{ 
		url:'/deliverRecord',
		templateUrl:'view/template/deliverRecord.html',
		controller:'deliverRecordCtrl'
	}).state('companyRegist',{ 
		url:'/companyRegist',
		templateUrl:'view/template/companyRegist.html',
		controller:'companyRegistCtrl'
	}).state('companyGetRecord',{ 
		url:'/companyGetRecord',
		templateUrl:'view/template/companyGetRecord.html',
		controller:'companyGetRecordCtrl'
	}).state('sendResume',{ 
		url:'/sendResume',
		templateUrl:'view/template/sendResume.html',
		controller:'sendResumeCtrl'
	});
	$urlRouterProvider.otherwise('main');	
}])